# Generated by Django 4.1.1 on 2022-09-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
