# Generated by Django 4.1.1 on 2022-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0002_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberType', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AudienceAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
